replicaCount: 1

image:
  repository: your-default-repo/backend
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
