apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/13-Cafeboo-GitOps
    targetRevision: main
    path: env/prod/ai
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
